token: <discord bot token>
database: <database file name>
init_bal: 100
bucks_per_pug: 5
bet_window: 10
discord_id: <bot discord id>
bullybot_discord_id: 359925573134319628
redfox_discord_id: 292031989773500416
pug_channel_id: 681756238190870601
bot_channel_id: 681756238190870601
twitch_client_id: <twitch client id>  # https://dev.twitch.tv/docs/authentication
twitch_auth_access_token: <twitch auth access token>  # https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-client-credentials-flow
